COL_TO_ATTR = {"RF Profile":["ap_g_radio_prof.profile-name","ap_a_radio_prof.profile-name","reg_domain_prof.profile-name"],
               "Device MAC": ["configuration_device.mac"],
               "Device Node": ["configuration_device.config_path"],
               "Device Model":["configuration_device.dev-model."],
               "Management Interface VLAN":['int_mgmt.int_mgmt_ip.vlanid'],
               "Management Interface IP":['int_mgmt.int_mgmt_ip.ipaddr'],
               "Management Interface DHCP":['int_mgmt.int_mgmt_dhcp'],
               "Management Interface Netmask":['int_mgmt.int_mgmt_ip.ipmask'],
               "VLAN ID":['vlan_id.id'],
               "Option 82":['vlan_id.option-82'],
               "VLAN Description":['vlan_id.vlan_id__descr.descr'],
               "PortChannel":['int_pc.id'],
               "PC Interfaces":['int_pc.int_pc_add_gig.slot/module/port'],
               "PC Trunk":['int_pc.int_pc_port_mode.port_mode'],
               "PC Access VLAN":['int_pc.int_pc_access_vlan.vlanId'],
               "PC Allowed VLANs":['int_pc.int_pc_allowed_vlan.WORD'],
               "PC Native VLAN":['int_pc.int_pc_vlan_native.vlanId'],
               "PC Jumbo Frames":['int_pc.int_pc_jumbo'],
               "PC Description":['int_pc.channel_int_desc.LINE'],
               "Loopback Interface":['int_loop.int_loop_ip.ipaddr'],
               "VLAN Name":['vlan_name.name'],
               "VLAN Associated IDs":['vlan_name_id.vlan-ids'],
               "IP Route":['ip_route.destip'],
               "Interface VLAN ID":['int_vlan.id'],
               "Interface VLAN IP":['int_vlan.int_vlan_ip.ipaddr'],
               "Interface VLAN IP Mask":['int_vlan.int_vlan_ip.ipmask'],
               "Interface VLAN IP DHCP":['int_vlan.int_vlan_ip.dhcp-client'],
               "Interface VLAN IP Helper Address":['int_vlan.int_vlan_ip_helper.address'],
               "NTP Server IP":['ntp_server_info.ip'],
               "NTP Server IPv6":['ntp_server_info.ip6'],
               "NTP Server FQDN":['ntp_server_info.fqdn'],
               "SNMPv3 Server Host IP":['snmp_ser_host_snmpv3.ipAddress'],
               "SNMPv3 Server Host Community":['snmp_ser_host_snmpv3.name'],
               "SNMPv3 Server Host Port":['snmp_ser_host_snmpv3.port'],
               "SNMP Server Community":['snmp_ser_community.name'],
               "DNS Server IPs":['ip_name_server.address'],
               "MC VLAN ID:":['ctrl.id'],
               "MC Loopback:":['ctrl.loopback'],
               "Gig Interface":['int_gig.slot/module/port'],
               "Gig Interface Speed":['int_gig.int_gig_speed.port_speed'],
               "Gig Interface Duplex":['int_gig.int_gig_duplex.duplex_mode'],
               "Gig Interface Description":['int_gig.int_gig_desc.LINE'],
               "Gig Interface Mode":['int_gig.int_gig_mode.port_mode'],
               "Gig Interface Access VLAN":['int_gig.int_gig_access_vlan.id'],
               "Gig Interface Allowed VLANs":['int_gig.int_gig_vlan.WORD'],
               "Gig Interface Native VLAN":['int_gig.int_gig_vlan_native.id'],
               "Gig Interface Jumbo Frames":['int_gig.int_gig_jumbo'],
               "Radius Server Name":['rad_server.rad_server_name'],
               "Radius Server Hostname":['rad_server.rad_host.host'],
               "Radius Server Key":['rad_server.rad_key.key'],
               "Radius Server Key":['rad_server.rad_key.key'],
               "Radius Server AuthPort":['rad_server.rad_authport.authport'],
               "Radius Server AcctPort":['rad_server.rad_accport.accport'],
               "Dot1x Profile":['dot1x_auth_prof.profile-name'],
               "Server Group Name":['server_group_prof.sg_name'],
               "Server Group Server Name":['server_group_prof.auth_serv.name'],
               "AAA Profile":['aaa_prof.profile-name'],
               "Server Derived Role":['aaa_prof.download_role'],
               "RFC 3576 Servers":['aaa_prof.rfc3576_client.rfc3576_server'],
               "MAC Auth":['mac_auth_prof.profile-name'],
               "Cluster Profile":['cluster_prof.profile-name'],
               "Cluster MC IP":['cluster_prof.cluster_controller.ip'],
               "Cluster MC VRRP IP":['cluster_prof.cluster_controller.vrrp_ip'],
               "Cluster MC VRRP VLAN":['cluster_prof.cluster_controller.vrrp_vlan'],
               "DHCP Pool Name": ['ip_dhcp_pool_cfg.pool_name'],
               "DHCP Pool DNS IP": ['ip_dhcp_pool_cfg.ip_dhcp_pool_cfg__dns.address1'],
               "DHCP Pool Default Router": ['ip_dhcp_pool_cfg.ip_dhcp_pool_cfg__def_rtr.address'],
               "DHCP Pool Subnet": ['ip_dhcp_pool_cfg.ip_dhcp_pool_cfg__net.subnet'],
               "DHCP Pool Subnet Mask": ['ip_dhcp_pool_cfg.ip_dhcp_pool_cfg__net.mask'],
               "DHCP Pool Start Address": ['ip_dhcp_pool_cfg.ip_dhcp_pool_cfg__range.address1'],
               "DHCP Pool End Address": ['ip_dhcp_pool_cfg.ip_dhcp_pool_cfg__range.address2'],
               "Standard ACL": ['acl_std.accname'],
               "Extended ACL": ['acl_ext.accname'],
               "Session ACL": ['acl_sess.accname'],
               "Standard ACEs": ['acl__std.acl_std__v4policy'],
               "Extended ACEs": ['acl__ext.acl_ext__v4policy'],
               "Session ACEs": ['acl__sess.acl_sess__v4policy'],
               "Netdest": ['netdst.dstname'],
               "Netdest Hosts":['netdst.netdst__host.address'],
               "Netdest Network":['netdst.netdst__network.address'],
               "Netdest Network Netmask":['netdst.netdst__network.netmask'],
               "Netdest Network Names":['netdst.netdst__name.host_name'],
               "Role":['role.rname'],
               "Role ACLs":['role.role__acl.pname'],
               "Role VLAN":['role.role__vlan.vlanstr'],
               "Role CP Profile":['role.role__cp.cp_profile_name'],
               "2.4 GHz Minimum": ["ap_g_radio_prof.eirp_min.eirp-min"],
               "2.4 GHz Maximum": ["ap_g_radio_prof.eirp_max.eirp-max"],
               "5 GHz Minimum": ["ap_a_radio_prof.eirp_min.eirp-min"],
               "5 GHz Maximum": ["ap_a_radio_prof.eirp_max.eirp-max"],
               "2.4 GHz Channels": ["reg_domain_prof.valid_11b_channel.valid-11g-channel"],
               "5 GHz Channels": ["reg_domain_prof.valid_11a_channel.valid-11a-channel"],
               "WLAN ESSID":["ssid_prof.profile-name","ssid_prof.essid","virtual_ap.profile-name"],
               "G Rates Required":["ssid_prof.g_basic_rates"],
               "G Rates Allowed":["ssid_prof.g_tx_rates"],
               "A Rates Required":["ssid_prof.a_basic_rates"],
               "A Rates Allowed":["ssid_prof.a_tx_rates"],
               "AP Group":["ap_group.profile-name"],
               "AP Group 5 GHz Profile":["ap_group.dot11a_prof.profile-name"],
               "AP Group Virtual APs":["ap_group.virtual_ap.profile-name"],
               "WMM EAP AC":["ssid_prof.wmm_eap_ac.wmm_ac"],
               "QoS Profile":["wlan_qos_prof.profile-name"],
               "QoS BW Allocation VAP":["wlan_qos_prof.bw_alloc.virtual-ap"],
               "QoS BW Allocation Share":["wlan_qos_prof.bw_alloc.share"],
               "ESSID":["ssid.essid.essid"]
}

BOOLEAN_DICT = {'Beacon':'ba', 'Probe':'pr', 'Low Data': 'ldata', 'High Data': 'hdata', 'Management':'mgmt',
                'Control': 'ctrl', 'All': 'all','True':True, 'False':False, 'Default':'default', 'Best Effort': 'best-effort',
                'Background': 'background', 'Voice': 'voice', 'Video': 'video'}

DEPENDENCY_DICT = {'ap_g_radio_prof':'dot11g_prof', 
                   'ap_a_radio_prof':'dot11a_prof',
                   'server_group':'dot1x_server_group',
                   'acl_sess':'role__acl',
                   'acl_std':'role__acl',
                   'acl_ext': 'role__acl',
                   'ap_group':'loc',
                   'accname':'pname'}